# Generated by Django 5.0.1 on 2024-02-06 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_perch_alter_feeder_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bird',
            name='perch',
            field=models.ManyToManyField(to='main_app.perch'),
        ),
    ]
